# Generated by Django 5.1.4 on 2026-07-15 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('general', 'General Physician'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('orthopedic', 'Orthopedic Surgeon'), ('pediatrician', 'Pediatrician'), ('neurologist', 'Neurologist'), ('psychiatrist', 'Psychiatrist'), ('dentist', 'Dentist'), ('ophthalmologist', 'Ophthalmologist'), ('ent', 'ENT Specialist')], default='general', max_length=30)),
                ('provider_name', models.CharField(default='HealthX Provider', max_length=150)),
                ('scheduled_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_reminder_sent', models.BooleanField(default=False)),
                ('email_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
